### ISSUE TITLE
Error on start: can't open '/var/log/crond.log'

### ISSUE THREAD

**Issue by djbingham** [n1b0r/docker-flow-proxy-letsencrypt#21]
Hello,

Thanks for the great-looking Let's Encrypt companion n1b0r, I love the way it is designed to work. I'm just having a problem getting it to run. I've tried versions 0.5 and 0.7. Both fail to start, with the following docker log output:
```
tail: can't open '/var/log/crond.log': No such file or directory
tail: no files
```

I haven't looked into the code but it seems like it just needs that file to exist before starting the service.

**Comment by n1b0r** [comment]
could you provide me your docker-compose file ?

**Comment by djbingham** [comment]
Hi @n1b0r, thanks for taking a look at this.

I made a slight mistake in my initial report. The container was failing to start on one system with a traceback showing in the logs when I had LOG set to true. This was the full log output in that case:
```
tail: can't open '/var/log/crond.log': No such file or directory
tail: no files
Traceback (most recent call last):
  File "/app/app.py", line 21, in <module>
    logging.getLogger('letsencrypt').setLevel(LEVELS[os.environ.get('LOG', 'info').lower()])
KeyError: ''
```

When I remove the LOG setting, I don't get the traceback and the container runs but still shows the first two lines (beginning `tail`) in the log file, including the `crond.log` error. I've stopped those errors by forking this project and creating `/var/log/crond.log` in the Dockerfile.

However, I now get errors from certbot when generating certificates:
```
2018-02-25 10:30:19,318;INFO;request for service: test_test
2018-02-25 10:30:19,319;INFO;letsencrypt support enabled.
2018-02-25 10:30:19,319;INFO;Letsencrypt support enabled, processing request: domains=rancher-01.default.bingham.uk0.bigv.io email=opensource@binghamsoftware.co.uk testing=None
2018-02-25 10:30:21,724;ERROR;Certbot return code: 1. Skipping
2018-02-25 10:30:21,725;ERROR;Error while generating certs for [u'rancher-01.default.bingham.uk0.bigv.io']
2018-02-25 10:30:21,733;ERROR;Combined certificate not found. Check logs for errors.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 81, in reconfigure
    client.process(args['letsencrypt.host'].split(','), args['letsencrypt.email'], testing=testing)
  File "/app/client_dfple.py", line 184, in process
    raise Exception('Combined cert not found')
Exception: Combined cert not found
```


Here is my docker-compose for the proxy services:
```
version: "3"

services:
    certbot:
        image: djbingham/docker-flow-proxy-letsencrypt:latest
        networks:
            - proxy
        environment:
            - DF_PROXY_SERVICE_NAME=${APP_NAME}_proxy
            - CERTBOT_OPTIONS=${CERTBOT_OPTIONS}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - proxy_certs:/etc/letsencrypt
        deploy:
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                - com.df.servicePath=/.well-known/acme-challenge
                - com.df.port=8080
            replicas: 1
            restart_policy:
                condition: on-failure

    proxy:
        image: vfarcic/docker-flow-proxy:18.01.18-98
        ports:
            - 80:80
            - 443:443
        networks:
            - proxy
            - public
        environment:
            - HTTPS_ONLY=true
            - LISTENER_ADDRESS=swarm-listener
            - MODE=swarm
            - SERVICE_NAME=${APP_NAME}_proxy
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    swarm-listener:
        image: vfarcic/docker-flow-swarm-listener:18.01.06-29
        networks:
            - proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DF_NOTIFY_CREATE_SERVICE_URL=http://certbot:8080/v1/docker-flow-proxy-letsencrypt/reconfigure
            - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

networks:
    proxy:
        external: false
    public:
        external: true

volumes:
    proxy_certs:
        external: false
```

Here is my docker-compose for the service I'm running to test the proxy:
```
version: "3"

services:
    certbot:
        image: djbingham/docker-flow-proxy-letsencrypt:latest
        networks:
            - proxy
        environment:
            - DF_PROXY_SERVICE_NAME=${APP_NAME}_proxy
            - CERTBOT_OPTIONS=${CERTBOT_OPTIONS}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - proxy_certs:/etc/letsencrypt
        deploy:
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                - com.df.servicePath=/.well-known/acme-challenge
                - com.df.port=8080
            replicas: 1
            restart_policy:
                condition: on-failure

    proxy:
        image: vfarcic/docker-flow-proxy:18.01.18-98
        ports:
            - 80:80
            - 443:443
        networks:
            - proxy
            - public
        environment:
            - HTTPS_ONLY=true
            - LISTENER_ADDRESS=swarm-listener
            - MODE=swarm
            - SERVICE_NAME=${APP_NAME}_proxy
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    swarm-listener:
        image: vfarcic/docker-flow-swarm-listener:18.01.06-29
        networks:
            - proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DF_NOTIFY_CREATE_SERVICE_URL=http://certbot:8080/v1/docker-flow-proxy-letsencrypt/reconfigure
            - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

networks:
    proxy:
        external: false
    public:
        external: true

volumes:
    proxy_certs:
        external: false
```

I made sure to set the variables referenced in each docker-compose:
```
APP_NAME=proxy CERTBOT_OPTIONS=--staging docker stack deploy -c docker-cloud.yml proxy
HOST=rancher-01.default.bingham.uk0.bigv.io CERTBOT_EMAIL=opensource@binghamsoftware.co.uk docker stack deploy -c docker-cloud.test.yml test
```

**Comment by djbingham** [comment]
OK, I've got it working now!

It seems I was setting the LOG value incorrectly before. Setting it to "debug" gave me nice debug logs from Certbot showing why it was failing to create certificates - it was failing to connect to verify my domain. I think this was caused by me setting Docker Flow Proxy to use HTTPS only. Once I removed `HTTPS_ONLY=true` from my proxy environment variables and `com.df.httpsOnly=true` from my test service labels Certbot started working and I got a certificate through.

I suppose the HTTPS_ONLY flags are used Docker Flow Proxy so prevent the `.well-known` check from Let's Encrypt to verify domain ownership before issuing certificates.

Is there any way to easily enforce HTTPS only via this setup or do I need to do that within each application behind the proxy?

**Comment by djbingham** [comment]
Ah actually, setting the label `com.df.httpsOnly=true` on my service container without the environment variable on Docker Flow Proxy seems to do the trick! I guess that tells Proxy to require HTTPS on requests going to that container but the Let's Encrypt companion temporarily reconfigures the proxy to send `.well-known` requests a different way.

@n1b0r Sorry to have bothered you. Hopefully my information will help if anyone else has a similar issue in future.

**Comment by n1b0r** [comment]
happy that you found your answer, well played !
