### ISSUE TITLE
Server error when proxy-le is contacted by swarm listener

### ISSUE THREAD

**Issue by qnm** [n1b0r/docker-flow-proxy-letsencrypt#4]
I'm unable get the default stack (from the README) working on my swarm.

My swarm listener is generating the following URL but when calling le-proxy this results in an error.

```
# docker logs 7264ba4a0061
2017/04/19 12:52:23 ERROR: Get http://proxy-le:8080/v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=dev%40digivizer.com&letsencrypt.host=whoami.dgvz.net&port=8000&serviceDomain=whoami.dgvz.net&serviceName=whoami_whoami&servicePath=%2F: dial tcp: i/o timeout
```

Here's what happens when I manually call `proxy-le` with my configuration:

```
docker exec  7264ba4a0061 wget -qO- "http://proxy-le:8080/v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=to dev%40digivizer.com&letsencrypt.host=whoami.dgvz.net&port=8000&serviceDomain=whoami.dgvz.net&serviceName=whoami_whoami&servicePath=%2F"
wget: bad header line: <title>Error response</title>
```

This resulting logs on the `proxy-le` image are:

```
INFO:letsencrypt:request for service: whoami_whoami
INFO:letsencrypt:letencrypt support enabled.
ERROR:letsencrypt:Certbot return code: 1. Skipping
INFO:werkzeug:10.0.0.3 - - [19/Apr/2017 23:10:13] "GET /v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=dev%40digivizer.com&letsencrypt.host=whoami.dgvz.net&port=8000&serviceDomain=whoami.dgvz.net&serviceName=whoami_whoami&servicePath=%2F HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 125, in reconfigure
    secret = docker_client.secrets().list(filters={'name': '{}.pem'.format(domain)})[-1]
IndexError: list index out of range
```
Any ideas? Have I mis-configured something?

**Comment by qnm** [comment]
Comment removed.

**Comment by n1b0r** [comment]
Could you provide your compose files please ?

**Comment by qnm** [comment]
@n1b0r Hey mate. Restarting my docker daemon appears to have fixed the issues...

I was using the reference `docker-compose.yml` as per the README.
