### ISSUE TITLE
flask errors when building from source

### ISSUE THREAD

**Issue by goncalo-oliveira** [n1b0r/docker-flow-proxy-letsencrypt#40]
Hi,

This issue isn't exactly related to this component, but I'm having a few issues that might be related to not having much experience with Python or Flask. However, I'm hoping that someone might be able to point me in the right direction.

I did a fork of this project, as I'm trying to add dns authentication other than OVH. I am able to execute the application directly from my machine, with the same version of Python and PIP. However, I am not able to get this running from the docker image. Even getting into the container and manually running `python /app/app.py` gets me this error.

```
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
2019-05-02 14:50:28,583;INFO; * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2019-05-02 14:50:28,584;INFO; * Restarting with stat
Traceback (most recent call last):
  File "/app/app.py", line 105, in <module>
    app.run(host='0.0.0.0', port=8080, debug=True, threaded=True)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python2.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/local/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```

To me, this error seems to be really generic and I still haven't figured out where the issue might be. I tried setting logs to debug, but that doesn't seem to give more details. Can anyone point me towards a positive direction?

Cheers

**Comment by goncalo-oliveira** [comment]
Closing this as I've figured out what the issue is... turns out the `app.py` line ending was modified to CRLF when cloning into a windows machine.
