### ISSUE TITLE
Error when requesting Certs

### ISSUE THREAD

**Issue by ghost** [n1b0r/docker-flow-proxy-letsencrypt#7]
Error seems to be identical with: https://github.com/n1b0r/docker-flow-proxy-letsencrypt/issues/4 

``` 
INFO:werkzeug:10.0.0.5 - - [29/Jun/2017 14:07:06] "GET /v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=XXX%40XXXr-iot.com&letsencrypt.host=XX-iot.com&port=5601&serviceDomain=XX.com&serviceName=kibana&servicePath=%2F&users=zisops%3Ag20inHamburg2017x HTTP/1.1" 500 -`
```
Removed our Domain names..

```
proxy-le.1.rk3l6vayct02@fluor    | Traceback (most recent call last):
proxy-le.1.rk3l6vayct02@fluor    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
proxy-le.1.rk3l6vayct02@fluor    |     return self.wsgi_app(environ, start_response)
proxy-le.1.rk3l6vayct02@fluor    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
proxy-le.1.rk3l6vayct02@fluor    |     response = self.handle_exception(e)
proxy-le.1.rk3l6vayct02@fluor    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
proxy-le.1.rk3l6vayct02@fluor    |     reraise(exc_type, exc_value, tb)
proxy-le.1.rk3l6vayct02@fluor    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
proxy-le.1.rk3l6vayct02@fluor    |     response = self.full_dispatch_request()
proxy-le.1.rk3l6vayct02@fluor    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
proxy-le.1.rk3l6vayct02@fluor    |     rv = self.handle_user_exception(e)
proxy-le.1.rk3l6vayct02@fluor    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
proxy-le.1.rk3l6vayct02@fluor    |     reraise(exc_type, exc_value, tb)
proxy-le.1.rk3l6vayct02@fluor    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
proxy-le.1.rk3l6vayct02@fluor    |     rv = self.dispatch_request()
proxy-le.1.rk3l6vayct02@fluor    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
proxy-le.1.rk3l6vayct02@fluor    |     return self.view_functions[rule.endpoint](**req.view_args)
proxy-le.1.rk3l6vayct02@fluor    |   File "/app/app.py", line 96, in reconfigure
proxy-le.1.rk3l6vayct02@fluor    |     combined = [x for x in certs if '.pem' in x][0]
proxy-le.1.rk3l6vayct02@fluor    | IndexError: list index out of range
```
I am sure it had worked 2 days before.. any ideas?

Startup:

```
sudo docker service create --name proxy-le \
    --network frontend \
    --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
    --detach=true \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/.well-known/acme-challenge \
    --label com.df.port=8080 nib0r/docker-flow-proxy-letsencrypt
```

**Comment by n1b0r** [comment]
Could you provide me more output logs ?

**Comment by ghost** [comment]
Hi, sure.. it is realy strange ..

```
proxy-le.1.8bne1pmopkef@astat    | INFO:werkzeug:10.0.0.14 - - [30/Jun/2017 07:44:54] "GET /v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=my-email.com&letsencrypt.host=stage.mydoman.com&port=4000&serviceDomain=stage.mydoman.com&serviceName=ziot-platform&servicePath=%2F HTTP/1.1" 200 -
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:request for service: kibana
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:letencrypt support enabled.
proxy-le.1.8bne1pmopkef@astat    | ERROR:letsencrypt:Certbot return code: 1. Skipping
proxy-le.1.8bne1pmopkef@astat    | INFO:werkzeug:10.0.0.14 - - [30/Jun/2017 07:45:02] "GET /v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=my-email.com&letsencrypt.host=kibana.stage.mydoman.com&port=5601&serviceDomain=kibana.stage.mydoman.com&serviceName=kibana&servicePath=%2F&users=zisops%3Ag20inHamburg2017x HTTP/1.1" 500 -
proxy-le.1.8bne1pmopkef@astat    | Traceback (most recent call last):
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
proxy-le.1.8bne1pmopkef@astat    |     return self.wsgi_app(environ, start_response)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.handle_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.full_dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.handle_user_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     return self.view_functions[rule.endpoint](**req.view_args)
proxy-le.1.8bne1pmopkef@astat    |   File "/app/app.py", line 96, in reconfigure
proxy-le.1.8bne1pmopkef@astat    |     combined = [x for x in certs if '.pem' in x][0]
proxy-le.1.8bne1pmopkef@astat    | IndexError: list index out of range
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:request for service: kibana
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:letencrypt support enabled.
proxy-le.1.8bne1pmopkef@astat    | ERROR:letsencrypt:Certbot return code: 1. Skipping
proxy-le.1.8bne1pmopkef@astat    | INFO:werkzeug:10.0.0.14 - - [30/Jun/2017 07:45:13] "GET /v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=my-email.com&letsencrypt.host=kibana.stage.mydoman.com&port=5601&serviceDomain=kibana.stage.mydoman.com&serviceName=kibana&servicePath=%2F&users=zisops%3Ag20inHamburg2017x HTTP/1.1" 500 -
proxy-le.1.8bne1pmopkef@astat    | Traceback (most recent call last):
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
proxy-le.1.8bne1pmopkef@astat    |     return self.wsgi_app(environ, start_response)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.handle_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.full_dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.handle_user_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     return self.view_functions[rule.endpoint](**req.view_args)
proxy-le.1.8bne1pmopkef@astat    |   File "/app/app.py", line 96, in reconfigure
proxy-le.1.8bne1pmopkef@astat    |     combined = [x for x in certs if '.pem' in x][0]
proxy-le.1.8bne1pmopkef@astat    | IndexError: list index out of range
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:request for service: kibana
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:letencrypt support enabled.
proxy-le.1.8bne1pmopkef@astat    | ERROR:letsencrypt:Certbot return code: 1. Skipping
proxy-le.1.8bne1pmopkef@astat    | INFO:werkzeug:10.0.0.14 - - [30/Jun/2017 07:45:24] "GET /v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=my-email.com&letsencrypt.host=kibana.stage.mydoman.com&port=5601&serviceDomain=kibana.stage.mydoman.com&serviceName=kibana&servicePath=%2F&users=zisops%3Ag20inHamburg2017x HTTP/1.1" 500 -
proxy-le.1.8bne1pmopkef@astat    | Traceback (most recent call last):
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
proxy-le.1.8bne1pmopkef@astat    |     return self.wsgi_app(environ, start_response)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.handle_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.full_dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.handle_user_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     return self.view_functions[rule.endpoint](**req.view_args)
proxy-le.1.8bne1pmopkef@astat    |   File "/app/app.py", line 96, in reconfigure
proxy-le.1.8bne1pmopkef@astat    |     combined = [x for x in certs if '.pem' in x][0]
proxy-le.1.8bne1pmopkef@astat    | IndexError: list index out of range
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:request for service: kibana
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:letencrypt support enabled.
proxy-le.1.8bne1pmopkef@astat    | ERROR:letsencrypt:Certbot return code: 1. Skipping
proxy-le.1.8bne1pmopkef@astat    | INFO:werkzeug:10.0.0.14 - - [30/Jun/2017 07:45:37] "GET /v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=my-email.com&letsencrypt.host=kibana.stage.mydoman.com&port=5601&serviceDomain=kibana.stage.mydoman.com&serviceName=kibana&servicePath=%2F&users=zisops%3Ag20inHamburg2017x HTTP/1.1" 500 -
proxy-le.1.8bne1pmopkef@astat    | Traceback (most recent call last):
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
proxy-le.1.8bne1pmopkef@astat    |     return self.wsgi_app(environ, start_response)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.handle_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.full_dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.handle_user_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     return self.view_functions[rule.endpoint](**req.view_args)
proxy-le.1.8bne1pmopkef@astat    |   File "/app/app.py", line 96, in reconfigure
proxy-le.1.8bne1pmopkef@astat    |     combined = [x for x in certs if '.pem' in x][0]
proxy-le.1.8bne1pmopkef@astat    | IndexError: list index out of range
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:request for service: kibana
proxy-le.1.8bne1pmopkef@astat    | INFO:letsencrypt:letencrypt support enabled.
proxy-le.1.8bne1pmopkef@astat    | ERROR:letsencrypt:Certbot return code: 1. Skipping
proxy-le.1.8bne1pmopkef@astat    | INFO:werkzeug:10.0.0.14 - - [30/Jun/2017 07:45:48] "GET /v1/docker-flow-proxy-letsencrypt/reconfigure?distribute=true&letsencrypt.email=my-email.com&letsencrypt.host=kibana.stage.mydoman.com&port=5601&serviceDomain=kibana.stage.mydoman.com&serviceName=kibana&servicePath=%2F&users=zisops%3Ag20inHamburg2017x HTTP/1.1" 500 -
proxy-le.1.8bne1pmopkef@astat    | Traceback (most recent call last):
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
proxy-le.1.8bne1pmopkef@astat    |     return self.wsgi_app(environ, start_response)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.handle_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
proxy-le.1.8bne1pmopkef@astat    |     response = self.full_dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.handle_user_exception(e)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
proxy-le.1.8bne1pmopkef@astat    |     reraise(exc_type, exc_value, tb)
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     rv = self.dispatch_request()
proxy-le.1.8bne1pmopkef@astat    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
proxy-le.1.8bne1pmopkef@astat    |     return self.view_functions[rule.endpoint](**req.view_args)
proxy-le.1.8bne1pmopkef@astat    |   File "/app/app.py", line 96, in reconfigure
proxy-le.1.8bne1pmopkef@astat    |     combined = [x for x in certs if '.pem' in x][0]
proxy-le.1.8bne1pmopkef@astat    | IndexError: list index out of range
```

**Comment by n1b0r** [comment]
hey,

Could you show me your stack.yml file or how you create the Kibana service ?

**Comment by ghost** [comment]
We have switched to an other solutions already, there was an error too "Limit exceeded by Lets encrypt" ... may be your container does not provide a catch block for this case?

**Comment by n1b0r** [comment]
The error was triggered because of the limit exceeded error ? Thats why certs were not generated ?
What other solution did you choose ?

Good luck !

**Comment by ghost** [comment]
Yes it looks like, we have switched to https://github.com/hamburml/docker-flow-letsencrypt , the script told us this error.. so i would guess that this was the reason why your container has started to throw the errors.

**Comment by n1b0r** [comment]
ok thanks for your report, will try to fix it soon.

**Comment by patrickleet** [comment]
I think limit exceeded is when a service crashes over and over infinitely and restarts every second or less, each time trying to request certs and you hit a rate limit. I've seen this happen with hamburml's as well. You need to wait a short while for the timeout placed on you by letsencrypt to expire. Adding a restart delay to container config should mitigate or prevent this from happening.
